language: node_js

node_js:
  - 12

stages:
  - test
  - name: deploy
    if: (branch == main) AND (type != pull_request)

jobs:
  include:
    - stage: test
      script:
        - yarn test:full
    - stage: deploy
      script:
        - yarn deploy
